In [33]:
import pandas as pd
import seaborn as sns
import numpy as np

In [2]:
df=pd.read_csv('train.csv')

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
gender=df[['Sex']]

In [5]:
gender.head()

      Sex
0    male
1  female
2  female
3  female
4    male

In [6]:
gender.isnull().sum()

Sex    0
dtype: int64

In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
le=LabelEncoder()

In [13]:
gender['Sex']=le.fit_transform(gender['Sex'])

C:\Users\sahil kumar\AppData\Local\Temp\ipykernel_17552\2493616698.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gender['Sex']=le.fit_transform(gender['Sex'])

In [14]:
gender.head()

   Sex
0    1
1    0
2    0
3    0
4    1

In [17]:
le.classes_

array([0, 1])

In [24]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [28]:
df.rename(
    columns={
        'Embarked':'Deck',
    },inplace=True)

In [29]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Deck
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [45]:
temp=df['Deck']

In [46]:
temp

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Deck, Length: 891, dtype: object

In [49]:
temp=pd.get_dummies(temp)

In [50]:
temp

         C      Q      S
0    False  False   True
1     True  False  False
2    False  False   True
3    False  False   True
4    False  False   True
..     ...    ...    ...
886  False  False   True
887  False  False   True
888  False  False   True
889   True  False  False
890  False   True  False

[891 rows x 3 columns]

In [52]:
tips=sns.load_dataset('tips')

In [54]:
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [59]:
from sklearn.preprocessing import OrdinalEncoder

In [77]:
# This tells scikit-learn you have 1 feature, containing these 4 categories
oe = OrdinalEncoder(categories=[['Thur', 'Fri', 'Sat', 'Sun']])

In [78]:
day=tips['day']

In [79]:
day.head()

0    Sun
1    Sun
2    Sun
3    Sun
4    Sun
Name: day, dtype: category
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [80]:
tips['day']=oe.fit_transform(tips[['day']])

In [81]:
tips

     total_bill   tip     sex smoker  day    time  size
0         16.99  1.01  Female     No  3.0  Dinner     2
1         10.34  1.66    Male     No  3.0  Dinner     3
2         21.01  3.50    Male     No  3.0  Dinner     3
3         23.68  3.31    Male     No  3.0  Dinner     2
4         24.59  3.61  Female     No  3.0  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
239       29.03  5.92    Male     No  2.0  Dinner     3
240       27.18  2.00  Female    Yes  2.0  Dinner     2
241       22.67  2.00    Male    Yes  2.0  Dinner     2
242       17.82  1.75    Male     No  2.0  Dinner     2
243       18.78  3.00  Female     No  0.0  Dinner     2

[244 rows x 7 columns]