In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
df=pd.read_csv('train.csv')

In [4]:
df = df.drop(columns=['Name', 'PassengerId', 'Ticket', 'Cabin'])

X_train, X_test, y_train, y_test = train_test_split(
    df.drop(columns=['Survived']), 
    df['Survived'], 
    test_size=0.2, 
    random_state=42, 
    stratify=df['Survived']
)

In [5]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [6]:
X_train['Age'] = X_train['Age'].fillna(X_train['Age'].median())
X_test['Age'] = X_test['Age'].fillna(X_train['Age'].median())

X_train['Embarked'] = X_train['Embarked'].fillna(X_train['Embarked'].mode()[0])
X_test['Embarked'] = X_test['Embarked'].fillna(X_train['Embarked'].mode()[0])

In [7]:
bins=[0,12,18,35,59,100]

In [8]:
labels = ['Child', 'Teen', 'Young Adult', 'Adult', 'Senior']

In [10]:
X_train['AgeGroup'] = pd.cut(X_train['Age'], bins=bins, labels=labels)
X_test['AgeGroup'] = pd.cut(X_test['Age'], bins=bins, labels=labels)

In [11]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [14]:
X_train['FamilySize'] = X_train['SibSp'] + X_train['Parch'] + 1   # +1 khud passenger ke liye
X_test['FamilySize'] = X_test['SibSp'] + X_test['Parch'] + 1

In [18]:
print(X_train[['Age','Sex','AgeGroup','SibSp','Parch','FamilySize','IsAlone','Embarked']].head())

      Age     Sex     AgeGroup  SibSp  Parch  FamilySize  IsAlone Embarked
692  28.5    male  Young Adult      0      0           1        1        S
481  28.5    male  Young Adult      0      0           1        1        S
527  28.5    male  Young Adult      0      0           1        1        S
855  18.0  female         Teen      0      1           2        0        S
801  31.0  female  Young Adult      1      1           3        0        S

In [15]:
X_train['IsAlone'] = (X_train['FamilySize'] == 1).astype(int)
X_test['IsAlone'] = (X_test['FamilySize'] == 1).astype(int)

In [19]:
X_train=pd.get_dummies(X_train,columns=['Sex', 'Embarked', 'AgeGroup'],drop_first=True)
X_test=pd.get_dummies(X_test,columns=['Sex', 'Embarked', 'AgeGroup'],drop_first=True)

In [22]:
missing_cols = set(X_train.columns) - set(X_test.columns)

missing_cols

In [23]:
missing_cols

set()

In [24]:
X_test = X_test[X_train.columns]

In [25]:
X_train[['Age', 'Fare', 'FamilySize']].head()

      Age      Fare  FamilySize
692  28.5   56.4958           1
481  28.5    0.0000           1
527  28.5  221.7792           1
855  18.0    9.3500           2
801  31.0   26.2500           3

In [26]:
from sklearn.preprocessing import StandardScaler

In [27]:
num_cols = ['Age', 'Fare', 'FamilySize']

In [28]:
Scaler=StandardScaler()

In [32]:
X_train[num_cols]=Scaler.fit_transform(X_train[num_cols])
X_test[num_cols]=Scaler.transform(X_test[num_cols])

In [33]:
X_train[['Age', 'Fare', 'FamilySize']].head()

          Age      Fare  FamilySize
692 -0.081135  0.513812   -0.556339
481 -0.081135 -0.662563   -0.556339
527 -0.081135  3.955399   -0.556339
855 -0.887827 -0.467874    0.073412
801  0.110934 -0.115977    0.703162

In [34]:
X_train[['Age', 'Fare', 'FamilySize']].describe()

                Age          Fare    FamilySize
count  7.120000e+02  7.120000e+02  7.120000e+02
mean  -2.494883e-18 -9.979533e-18  2.370139e-17
std    1.000703e+00  1.000703e+00  1.000703e+00
min   -2.238460e+00 -6.625632e-01 -5.563386e-01
25%   -5.805160e-01 -4.981542e-01 -5.563386e-01
50%   -8.113533e-02 -3.615930e-01 -5.563386e-01
75%    4.950731e-01 -1.707070e-02  7.341193e-02
max    3.875496e+00  1.000533e+01  5.741166e+00